set(SRC_FILES
    Animation.cpp
    App.cpp
    Attack/Attack.cpp
    Attack/AttackManager.cpp
    Attack/EffectAttack.cpp
    Attack/EffectAttackPool.cpp
    Attack/Projectile.cpp
    Attack/ProjectilePool.cpp
    Beacon.cpp
    Camera.cpp
    CollisionComponentStruct.cpp
    Components/AiComponent.cpp
    Components/AnimationComponent.cpp
    Components/AttackComponent.cpp
    Components/ChestComponent.cpp
    Components/CollisionComponent.cpp
    Components/DoorComponent.cpp
    Components/EnemyAI/AttackStrategy.cpp
    Components/EnemyAI/MoveStrategy.cpp
    Components/FlickerComponent.cpp
    Components/FollowerComponent.cpp
    Components/HealthComponent.cpp
    Components/InputComponent.cpp
    Components/InteractableComponent.cpp
    Components/MovementComponent.cpp
    Components/ProjectileComponent.cpp
    Components/SkillComponent.cpp
    Components/SpikeComponent.cpp
    Components/StateComponent.cpp
    Components/TalentComponent.cpp
    Creature/Character.cpp
    Cursor.cpp
    Factory/CharacterFactory.cpp
    Factory/Factory.cpp
    Factory/RoomFactory.cpp
    Factory/RoomObjectFactory.cpp
    Factory/WeaponFactory.cpp
    ImagePoolManager.cpp
    Loader.cpp
    ObserveManager/AudioManager.cpp
    ObserveManager/InputManager.cpp
    ObserveManager/TrackingManager.cpp
    Room/CollisionOptimizer.cpp
    Room/DungeonMap.cpp
    Room/DungeonRoom.cpp
    Room/DungeonRoom_CollisionOptimization.cpp
    Room/LobbyRoom.cpp
    Room/MonsterRoom.cpp
    Room/MonsterRoomTestUI.cpp
    Room/PortalRoom.cpp
    Room/Room.cpp
    Room/RoomCollisionManager.cpp
    Room/RoomInteractionManager.cpp
    Room/RoomLayoutManager.cpp
    Room/StartingRoom.cpp
    Room/UniformGrid.cpp
    SaveManager.cpp
    Scene/Complete_Scene.cpp
    Scene/DungeonLoading_Scene.cpp
    Scene/Dungeon_Scene.cpp
    Scene/Lobby_Scene.cpp
    Scene/MainMenu_Scene.cpp
    Scene/Result_Scene.cpp
    Scene/Scene.cpp
    Scene/SceneManager.cpp
    Scene/Test_Scene_JX.cpp
    Scene/Test_Scene_KC.cpp
    Skill/FullFirepower.cpp
    Struct/CircleShape.cpp
    Struct/RectShape.cpp
    StructType.cpp
    Structs/DeathEventInfo.cpp
    TalentDatabase.cpp
    Tool/Tool.cpp
    TriggerStrategy/AttackTriggerStrategy.cpp
    TriggerStrategy/BlockProjectileStrategy.cpp
    TriggerStrategy/KnockOffTriggerStrategy.cpp
    TriggerStrategy/ReflectTriggerStrategy.cpp
    TriggerStrategy/SpeedZoneStrategy.cpp
    UIPanel/GameHUDPanel.cpp
    UIPanel/MenuHUDPanel.cpp
    UIPanel/MinimapPanel.cpp
    UIPanel/PausePanel.cpp
    UIPanel/PlayerStatusPanel.cpp
    UIPanel/SettingPanel.cpp
    UIPanel/TalentSelectionPanel.cpp
    UIPanel/UIButton.cpp
    UIPanel/UIManager.cpp
    UIPanel/UIPanel.cpp
    UIPanel/UISlider.cpp
    Util/Timer.cpp
    Weapon/GunWeapon.cpp
    Weapon/MeleeWeapon.cpp
    Weapon/Weapon.cpp
    main.cpp
    nGameObject.cpp
)

set(INCLUDE_FILES
    Animation.hpp
    App.hpp
    Attack/Attack.hpp
    Attack/AttackManager.hpp
    Attack/EffectAttack.hpp
    Attack/EffectAttackPool.hpp
    Attack/Projectile.hpp
    Attack/ProjectilePool.hpp
    Beacon.hpp
    Camera.hpp
    Components/AiComponent.hpp
    Components/AllComponentInclude.hpp
    Components/AnimationComponent.hpp
    Components/AttackComponent.hpp
    Components/ChestComponent.hpp
    Components/CoinComponent.hpp
    Components/CollisionComponent.hpp
    Components/Component.hpp
    Components/DoorComponent.hpp
    Components/EffectAttackComponent.hpp
    Components/EnemyAI/AttackStrategy.hpp
    Components/EnemyAI/MoveStrategy.hpp
    Components/EnemyAI/UtilityStrategy.hpp
    Components/FlickerComponent.hpp
    Components/FollowerComponent.hpp
    Components/HealthComponent.hpp
    Components/InputComponent.hpp
    Components/InteractableComponent.hpp
    Components/MovementComponent.hpp
    Components/ProjectileComponent.hpp
    Components/SkillComponent.hpp
    Components/SpikeComponent.hpp
    Components/StateComponent.hpp
    Components/TalentComponet.hpp
    Components/TriggerComponent.hpp
    Components/walletComponent.hpp
    Creature/Character.hpp
    Cursor.hpp
    EnumTypes.hpp
    Factory/CharacterFactory.hpp
    Factory/Factory.hpp
    Factory/RoomFactory.hpp
    Factory/RoomObjectFactory.hpp
    Factory/WeaponFactory.hpp
    GameMechanism/Talent.hpp
    GameMechanism/TalentDatabase.hpp
    ImagePoolManager.hpp
    Loader.hpp
    Motion.hpp
    ObserveManager/AudioManager.hpp
    ObserveManager/EventManager.hpp
    ObserveManager/IManager.hpp
    ObserveManager/InputManager.hpp
    ObserveManager/ObserveManager.hpp
    ObserveManager/TrackingManager.hpp
    Observer.hpp
    Override/nGameObject.hpp
    RandomUtil.hpp
    Room/CollisionOptimizer.hpp
    Room/DungeonMap.hpp
    Room/DungeonRoom.hpp
    Room/LobbyRoom.hpp
    Room/MonsterRoom.hpp
    Room/MonsterRoomTestUI.hpp
    Room/PortalRoom.hpp
    Room/Room.hpp
    Room/RoomCollisionManager.hpp
    Room/RoomInteractionManager.hpp
    Room/RoomLayoutManager.hpp
    Room/StartingRoom.hpp
    Room/UniformGrid.hpp
    RoomObject/DestructibleBox.hpp
    RoomObject/WallObject.hpp
    SaveManager.hpp
    Scene/Complete_Scene.hpp
    Scene/DungeonLoading_Scene.hpp
    Scene/Dungeon_Scene.hpp
    Scene/Lobby_Scene.hpp
    Scene/MainMenu_Scene.hpp
    Scene/Result_Scene.hpp
    Scene/Scene.hpp
    Scene/SceneManager.hpp
    Scene/Test_Scene_JX.hpp
    Scene/Test_Scene_KC.hpp
    Skill/FullFirepower.hpp
    Skill/Skill.hpp
    StructType.hpp
    Structs/AreaShape.hpp
    Structs/BlockProjectileEventInfo.hpp
    Structs/CircleShape.hpp
    Structs/CollisionComponentStruct.hpp
    Structs/DeathEventInfo.hpp
    Structs/EventInfo.hpp
    Structs/InteractionComponentStruct.hpp
    Structs/KnockOffEventInfo.hpp
    Structs/PositionChangedEvent.hpp
    Structs/RectShape.hpp
    Structs/ReflectProjectileEventInfo.hpp
    Structs/SpeedChangeEventInfo.hpp
    Structs/TakeDamageEventInfo.hpp
    Structs/ValueChangedEvent.hpp
    Tool/Tool.hpp
    TriggerStrategy/AttackTriggerStrategy.hpp
    TriggerStrategy/BlockProjectileStrategy.hpp
    TriggerStrategy/ITriggerStrategy.hpp
    TriggerStrategy/KnockOffTriggerStrategy.hpp
    TriggerStrategy/ReflectTriggerStrategy.hpp
    TriggerStrategy/SpeedZoneStrategy.hpp
    UIPanel/GameHUDPanel.hpp
    UIPanel/MenuHUDPanel.hpp
    UIPanel/MinimapPanel.hpp
    UIPanel/PausePanel.hpp
    UIPanel/PlayerStatusPanel.hpp
    UIPanel/ResultPanel.hpp
    UIPanel/SettingPanel.hpp
    UIPanel/TalentSelectionPanel.hpp
    UIPanel/UIButton.hpp
    UIPanel/UIManager.hpp
    UIPanel/UIPanel.hpp
    UIPanel/UISlider.hpp
    Util/Timer.hpp
    Weapon/GunWeapon.hpp
    Weapon/MeleeWeapon.hpp
    Weapon/Weapon.hpp
)

set(INLINE_FILES
    Override/nGameObject.inl
)
