set(SRC_FILES
    Animation.cpp
    App.cpp
    Beacon.cpp
    BulletManager.cpp
    Camera.cpp
    Component/AnimationComponent.cpp
    Component/AttackAI.cpp
    Component/AttackComponent.cpp
    Component/CollisionComponent.cpp
    Component/FollowerComponent.cpp
    Component/HealthComponent.cpp
    Component/InputComponent.cpp
    Component/InteractableComponent.cpp
    Component/MovementComponent.cpp
    Component/SkillComponent.cpp
    Component/StateComponent.cpp
    Component/TalentComponent.cpp
    Creature/Character.cpp
    Cursor.cpp
    Factory/CharacterFactory.cpp
    Factory/Factory.cpp
    Factory/RoomFactory.cpp
    Factory/RoomObjectFactory.cpp
    Factory/WeaponFactory.cpp
    ObseveManager/InputManager.cpp
    Room/LobbyRoom.cpp
    Room/Room.cpp
    Room/RoomCollisionManager.cpp
    Room/RoomInteractionManager.cpp
    RoomObject/ObstacleObject.cpp
    Scene/Complete_Scene.cpp
    Scene/DungeonLoading_Scene.cpp
    Scene/Dungeon_Scene.cpp
    Scene/Lobby_Scene.cpp
    Scene/MainMenu_Scene.cpp
    Scene/Result_Scene.cpp
    Scene/SceneManager.cpp
    Scene/Test_Scene_JX.cpp
    Scene/Test_Scene_KC.cpp
    Skill/FullFirepower.cpp
    Tool/Tool.cpp
    Weapon/Bullet.cpp
    Weapon/GunWeapon.cpp
    Weapon/MeleeWeapon.cpp
    Weapon/Weapon.cpp
    main.cpp
)

set(INCLUDE_FILES
    Animation.hpp
    App.hpp
    Beacon.hpp
    BulletManager.hpp
    Camera.hpp
    Components/AiComponent.hpp
    Components/AnimationComponent.hpp
    Components/AttackAI.hpp
    Components/AttackComponent.hpp
    Components/CollisionComponent.hpp
    Components/Component.hpp
    Components/FollowerComponent.hpp
    Components/HealthComponent.hpp
    Components/InputComponent.hpp
    Components/InteractableComponent.hpp
    Components/MovementComponent.hpp
    Components/SkillComponent.hpp
    Components/StateComponent.hpp
    Components/TalentComponet.hpp
    Creature/Character.hpp
    Cursor.hpp
    EnumTypes.hpp
    Factory/CharacterFactory.hpp
    Factory/Factory.hpp
    Factory/RoomFactory.hpp
    Factory/RoomObjectFactory.hpp
    Factory/WeaponFactory.hpp
    GameMechanism/StatusEffect.hpp
    GameMechanism/Talent.hpp
    GameMechanism/TalentDatabase.hpp
    Motion.hpp
    ObserveManager/InputManager.hpp
    ObserveManager/ObserveManager.hpp
    ObserveManager/TrackingManager.hpp
    Observer.hpp
    Override/nGameObject.hpp
    Room/LobbyRoom.hpp
    Room/Room.hpp
    Room/RoomCollisionManager.hpp
    Room/RoomInteractionManager.hpp
    RoomObject/ObstacleObject.hpp
    RoomObject/RoomObject.hpp
    Scene/Complete_Scene.hpp
    Scene/DungeonLoading_Scene.hpp
    Scene/Dungeon_Scene.hpp
    Scene/Lobby_Scene.hpp
    Scene/MainMenu_Scene.hpp
    Scene/Result_Scene.hpp
    Scene/Scene.hpp
    Scene/SceneManager.hpp
    Scene/Test_Scene_JX.hpp
    Scene/Test_Scene_KC.hpp
    Skill/FullFirepower.hpp
    Skill/Skill.hpp
    Tool/Tool.hpp
    Weapon/Bullet.hpp
    Weapon/GunWeapon.hpp
    Weapon/MeleeWeapon.hpp
    Weapon/Weapon.hpp
)

set(INLINE_FILES
    Override/nGameObject.inl
)
