set(SRC_FILES
    Animation.cpp
    App.cpp
    Beacon.cpp
    Camera.cpp
    Component/CollisionComponent.cpp
    Component/FollowerComponent.cpp
    Component/MovementComponent.cpp
    Creature/Character.cpp
    Creature/Enemy.cpp
    Creature/Player.cpp
    Cursor.cpp
    Factory/CharacterFactory.cpp
    Factory/Factory.cpp
    Factory/WeaponFactory.cpp
    Room/Room.cpp
    Room/RoomCollisionManager.cpp
    RoomObject/ObstacleObject.cpp
    Scene/Complete_Scene.cpp
    Scene/DungeonLoading_Scene.cpp
    Scene/Dungeon_Scene.cpp
    Scene/Lobby_Scene.cpp
    Scene/MainMenu_Scene.cpp
    Scene/Result_Scene.cpp
    Scene/SceneManager.cpp
    Scene/Test_Scene_JX.cpp
    Scene/Test_Scene_KC.cpp
    Tool/CollisionBox.cpp
    Tool/HitBox.cpp
    Tool/Tool.cpp
    Weapon/Weapon.cpp
    main.cpp
)

set(INCLUDE_FILES
    Animation.hpp
    App.hpp
    Beacon.hpp
    Camera.hpp
    Components/CollisionComponent.hpp
    Components/Component.hpp
    Components/FollowerComponent.hpp
    Components/MovementComponent.hpp
    Creature/Character.hpp
    Creature/Enemy.hpp
    Creature/Player.hpp
    Cursor.hpp
    Factory/CharacterFactory.hpp
    Factory/Factory.hpp
    Factory/WeaponFactory.hpp
    GameMechanism/Skill.hpp
    GameMechanism/StatusEffect.hpp
    GameMechanism/Talent.hpp
    Motion.hpp
    Override/nGameObject.hpp
    Room/Room.hpp
    Room/RoomCollisionManager.hpp
    RoomObject/ObstacleObject.hpp
    RoomObject/RoomObject.hpp
    Scene/Complete_Scene.hpp
    Scene/DungeonLoading_Scene.hpp
    Scene/Dungeon_Scene.hpp
    Scene/Lobby_Scene.hpp
    Scene/MainMenu_Scene.hpp
    Scene/Result_Scene.hpp
    Scene/Scene.hpp
    Scene/SceneManager.hpp
    Scene/Test_Scene_JX.hpp
    Scene/Test_Scene_KC.hpp
    Tool/CollisionBox.hpp
    Tool/CollisionManager.hpp
    Tool/HItBox.hpp
    Tool/Tool.hpp
    Weapon/Weapon.hpp
)

set(INLINE_FILES
    Override/nGameObject.inl
)
